services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: true
      TYPE: FABRIC
      VERSION: 1.20.1
      FABRIC_VERSION: 0.16.10
      MAX_MEMORY: "16G"
      MOTD: "Crypton: Miku The Gathering"
      DIFFICULTY: "normal"
    ports:
      - "9001:9001"
      - "9003:9003/udp"
      - "8123:8123"
    volumes:
      - /data/docker/mikuthegathering:/data
networks:
  net_10.0.0.253:
    driver_opts:
      com.docker.network.host_ipv4: 10.0.0.252
