services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: true
      TYPE: NEOFORGE
      VERSION: 1.21.1
      NEOFORGE_VERSION: 21.1.93
      MAX_MEMORY: "32G"
      MOTD: "Crypton: All The Mods 10"
      DIFFICULTY: "normal"
    ports:
      - "25565:25565"
    volumes:
      - /data/docker/atm10:/data
networks:
  net_10.0.0.253:
    driver_opts:
      com.docker.network.host_ipv4: 10.0.0.252
