services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.20.1
      FABRIC_VERSION: latest
      MAX_MEMORY: "16G"
      MOTD: ":3"
      DIFFICULTY: "easy"
    volumes:
      - /data/docker/bcg-p/data:/data  
